SET SERVEROUTPUT ON;
SET VERIFY OFF
-- Ejemplo 1
DECLARE BEGIN
    dbms_output.put_line('Hola Mundo PL/SQL');
END;
/
 
-- Declaracion de variables
/*
NUMBER → números, enteros o decimales.

VARCHAR2 → texto (palabras, nombres, frases).

DATE → fechas.

BOOLEAN → verdadero/falso.

DECLARE → donde defines tus variables.

:= → le das un valor a la variable.

|| → une texto y valores para mostrarlos juntos.
*/
DECLARE
    nombre VARCHAR2(50);
    edad   NUMBER;
BEGIN
    nombre := 'Samu';
    edad := '23';
    dbms_output.put_line('Hola mi nombres es ' || nombre);
    dbms_output.put_line('tengo '
                         || edad
                         || ' años');
END;
/

-- Condicionales
/*
A veces quieres que tu programa tome decisiones según condiciones.

Usamos IF para esto: “Si esto pasa, haz esto; si no, haz otra cosa”.
*/

DECLARE
    edad NUMBER := '23';
BEGIN
    IF edad < 18 THEN
        dbms_output.put_line('Eres menor de edad');
    ELSIF
        edad >= 18
        AND edad < 30
    THEN
        dbms_output.put_line('Eres un adulto pero eres Joven');
    ELSE
        dbms_output.put_line('Eres adulto avanzado');
    END IF;
END;
/

--Bucles (loops)

--loop basico
declare
  i number := 1;
begin
  loop
    dbms_output.put_line('Numero: ' || i);
    i:= i+1;
    exit when i > 5 ;
  end loop;
end;
/

-- loop for
begin 
  for i in 1..5 loop
  dbms_output.put_line('Numero For LOOP: ' || i);
  end loop;
end;
/

-- Ejercicio Numeros Pares con Bucle 
/*
Mod = Es una funcion de Pl que devuelve el resro de una division entre dos numeros'
*/
begin
  for i in 2..60 loop
  if mod(i,2) = 0 then 
  dbms_output.put_line('Los pares son:' || i);
  end if;
  end loop;
end;
/

-- Numeros impares 

begin
  for i in 2..60 loop
  if mod(i,2) != 0 then 
  dbms_output.put_line('Los impares son:' || i);
  end if;
  end loop;
end;
/

-- Crearemos unas tablas para poder practicar lo siguiente 
CREATE TABLE Usuarios (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID único auto incrementable
    Nombre VARCHAR2(50) NOT NULL,                             -- Nombre del usuario
    Edad NUMBER,                                              -- Edad del usuario
    Ciudad VARCHAR2(50)                                       -- Ciudad del usuario
);
INSERT INTO Usuarios (Nombre, Edad, Ciudad) VALUES ('Samu', 23, 'Dublín');
INSERT INTO Usuarios (Nombre, Edad, Ciudad) VALUES ('Marta', 23, 'Cork');
INSERT INTO Usuarios (Nombre, Edad, Ciudad) VALUES ('Ericky', 31, 'Galway');

-- Guardar los cambios
COMMIT;

select * from usuarios;

-- Ahora podemos trabajar sobre tablas en BBDD

declare 
  nombreUsuario Usuarios.Nombre%Type;
  edadUsuario Usuarios.Edad%Type;
begin
  nombreUsuario := 'Carlos';
  edadUsuario := '78';
  
  dbms_output.put_line('Nombre: ' || nombreUsuario);
  dbms_output.put_line('Edad: ' || edadUsuario);
end;
/

  
-- Tambien podremos traer datos de la tabla con select into:

declare
  nombreUsuario Usuarios.Nombre%Type;
  edadUsuario Usuarios.Edad%Type;
begin
  select Nombre, Edad
  into nombreUsuario,edadUsuario
  from Usuarios
  where Edad = 23 and rownum= 1; -- esto se pone para que solo muestre la primera fila que encuentre la otra opcion es que si hay mas coincidencias y quieres mostrar todas habria que hacer un loop
  
  dbms_output.put_line('El usuario se llama '||nombreUsuario || ' y Tiene ' ||edadusuario|| ' años');
end;
/

-- Mas practica de lo mismo
declare 
  nombreUsuario Usuarios.Nombre%TYPE;
  ciudadUsuario Usuarios.Ciudad%Type;
begin
  select Nombre, Ciudad
  into nombreUsuario, ciudadUsuario
  from Usuarios
  where rownum =1;
  
  if ciudadusuario = 'Dublín' then
   dbms_output.put_line('El usuario '||nombreusuario||' vive en  '||ciudadUsuario);
   ELSIF ciudadUsuario = 'Cork' then
   dbms_output.put_line('CORKINENSE');
  else
   dbms_output.put_line('El usuario '||nombreUsuario|| 'vive en ' ||ciudadUsuario);
   end if;
end;
/
  
-- Mas restrictivo y con un bucle por una doble condicion

BEGIN
  FOR u IN (SELECT Nombre, Ciudad FROM Usuarios) LOOP
    IF u.Nombre = 'Marta' THEN
        DBMS_OUTPUT.PUT_LINE('El usuario ' || u.Nombre || ' vive en ' || u.Ciudad);
    END IF;
  END LOOP;
END;
/

-- Solicitud de datos por consola

declare
  nombre varchar2(20);
  edad number;
begin
  nombre:='&Nombre';
  edad:=&edad;
  
  dbms_output.put_line('El usuario a ingresado su nombre que es '|| nombre || ' y su edad que es '|| edad); 
end;
/

-- usar RowType con cursores explicitos

/*
CURSOR cursor_alumnos IS SELECT ...
→ defines el cursor con la consulta que quieres recorrer.

u cursor_alumnos%ROWTYPE;
→ crea una variable u que tiene exactamente las mismas columnas y tipos que las filas que devuelve el cursor.

OPEN cursor_alumnos;
→ ejecuta la consulta y prepara el conjunto de resultados.

FETCH cursor_alumnos INTO u;
→ obtiene la siguiente fila del cursor y guarda los valores en u.

EXIT WHEN cursor_alumnos%NOTFOUND;
→ sale del bucle cuando ya no quedan filas que leer.

dbms_output.put_line(...)
→ muestra la información de cada fila.

CLOSE cursor_alumnos;
→ libera la memoria del cursor (buena práctica).
*/
declare
  cursor cursor_alumnos is
  select nombre, edad, ciudad 
  from usuarios;
  u cursor_alumnos%Rowtype;
  
begin
  open cursor_alumnos;
    loop
      fetch cursor_alumnos into u;
      exit when cursor_alumnos%NOTFOUND;
      
      dbms_output.put_line('Usuario: ' || u.nombre || '  con la edad de  ' || u.edad || '  viviendo en la Ciudad de  ' || u.ciudad);
    end loop;
  close cursor_alumnos;
end;
/
 

  
  
  
